apiVersion: apps/v1
kind: Deployment
metadata:
  name: sycamore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sycamore-api
  template:
    metadata:
      labels:
        app: sycamore-api
    spec:
      containers:
        - name: api
          image: node:18-alpine
          command:
            [
              "node",
              "-e",
              "const http = require('http'); http.createServer((req, res) => { res.writeHead(200); res.end('OK'); }).listen(3000);",
            ]
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
